name: gym_book
description: A way to keep track of your gym records.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.18.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.0.17
  flutter_bloc: ^8.1.1
  get_it: ^7.2.0
  mocktail: ^0.3.0

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
